version: '2'

services:
  <%= conf.webpackServerName %>:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    volumes:
      - "../project:/app/project"
      - "../reports:/app/reports"
      - "../dist:/app/dist"
    environment:
      - NODE_ENV
      - CI
    command: "npm start"
