language: node_js
node_js:
- '5'
notifications:
  slack:
    rooms:
      secure: H/GJtf/yYzYTfbS1jwUtco8gAmxDTpsPN6PXAMNdK6gKVcS2j9qt0gpuDxxXlI2mH8CdmFOpPAzHxQNXjF7Fghg+Iqlmdpc8+w1Zlp6+mtJsR2Hn+KPk+MyHhAlhETnNYTJ1U+mjc22tMBZt9uaVThyoPl2PiGPz1+IOKTJvLulDG4BCbO9km6T24kNnBSnRNrvGDGvckqRZYoL0DbGy35sw01bM1+Z0AQYhYUK6++2It9lB9dPQFtcUVoJeyWmEUWWVpy5D9/PVdC+lOT2L7ZNKQD2oClePVZ3RdOSltCWbcdOLU+jzEWBx2EdhU0JVLCjXGmjDpOL5Sb0PIfZ0aouuLflLeRoLnhbuISv00qMbFRvWj9RR9IgSlHo/Z1ie9uwCVDpTobo5/sC+y+naKdtElL+g4ZKT4KDejDxSfoMSOIOfFmv7JKvDX+3R4TEfabl0mZstdLV4TMypMO5o6Blm0RgOTTWw0iGuIlxUGWMRLQyW+kCGvPEnbIAk1nkvBSDz5qSfpLHQFD5u27gu5h3yAoIJO1xDV05YRYCUru1arGUAh6VVOHi+2gCCYnYceZ1LBbAPD4uXgEnBG4VVQl4q6TMFrRkuZCu2ZkJqwXMsBUToc55+uVywHI9DLNRB51uv2IQDnH7/tYiLgBrOvaBbO6sG8o1dQGNqf1pwsaE=
  email: false
install:
- npm install
script:
- npm run build
deploy:
  provider: npm
  email: zsolt@zsoltmolnar.hu
  api_key:
    secure: mHD+55byW+vVJ/c3GtiQAFzCacAv5WMZoEwd61Yp8MF7HH8WoxO7SAU6lx76/K8WajBqfkDUT4NQhQAKaUgnMhW48lywIux7PdTitetPBgglYqjLAN9A+oIf9CYNeyWnb77BV5P5pnwJxXu4QY3M/XrCoFBWtMm9EnXwAiczQ0BGpTS0ACee2A6UOHuOw/w5zfYYOPJEsIBlY/AdQTj/OcDVJ3QPxAULX1eJMrdALo9qitOrZy4ktfk4J/6Bg2caIXiJLGGATPKlf88vM6wXu5qp7bIwTainhBa5oBLPQN0GVblVf16RrvNluINJfbZIG9luk50hWmILuJe19OZeKZ7YW8Pl1qQJxD8u4mY4S7LCr2//h/O0un46CrRuwFlLv+pvZhg6bCMkN7LTJuSqi2/pZU8y0ZzKRjBwfYhhA0OyOrGH0/1axidVXqeMA/0nTxlMJ4WsJ/RFXWdNyLqk3aN5BVOjAD6JlcI/f2E297cgFYvqd/dHgCFoiCsZOt6QD0SXxAXmzovNLK7kO0hoP2kQAFcxd78M+8HwMR1p2uG+366YkFuAxRhsLAbPGbxWejgay+jjAVQX1oyCfnmdUVhpG8rJirTrrGUGpiLhuyYn4+vwoWki/RkvkQv99C5rSx9qjk8+DGA/U1gbA0Axoq+82c2R/zXMRUjS8akJf+A=
  on:
    tags: true
    repo: garlictech/generator-garlic-webapp
