version: '2'

services:
  <%= c.scope %>.<%= c.appNameKC %>.dev:
    build:
      context: ../
      dockerfile: Dockerfile.dev
    env_file:
      - "./service.env"
      - "../tokens.env"
    volumes:
      - "../:/app/project"
    command: "gulp"
