version: '2'

services:
  <%= c.scope %>.<%= c.appNameKC %>.dev:
    build:
      context: ../
      dockerfile: Dockerfile.dev
    env_file:
      - "./service.env"
      - "./tokens.env"
    environment:
      - NODE_ENV
    volumes:
      - "../project:/app/project"
    command: "gulp"
