version: '2'

services:
  <%= c.appNameKC %>.prod:
    image: <%= c.dockerRepo %>/<%= c.appNameKC %>:latest
    env_file:
      - "./service.env"
      - "./tokens.env"
    ports:
      - "3000:3000"
