version: '2'

services:
  <%= c.scope %>.<%= c.appNameKC %>.dev:
    build:
      context: ../
      dockerfile: Dockerfile.dev
    env_file:
      - "./service.env"
      - "./tokens.env"
    environment:
      - NODE_ENV
    volumes:
      - "../src:/app/src"
      - "../test:/app/test"
      - "../hooks:/app/hooks"
      - "../dist:/app/dist"
    command: "gulp"
