version: '2'

services:
  <%= c.appNameKC %>.dev:
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        NPM_TOKEN: $NPM_TOKEN_<%= c.scopeCC %>
    env_file:
      - "./service.env"
    environment:
      - NODE_ENV
    volumes:
      - "../project:/app/project"
      - "../dist:/app/dist"
      - "../hooks:/app/hooks"
    command: "gulp"
