language: node_js
node_js:
- '5'

notifications:
  slack: <add slack notifiction key>

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

install:
  - npm install

script:
  - npm run build && npm run unittest

# Uncomment it only if needed, not to waste time with unnecessary install.
# env:
#   - CXX=g++-4.8

# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - g++-4.8

deploy:
  provider: npm
  email: contact@garlictech.com
  on:
    tags: true
  api_key: <add npm token>
   
env:  
  global:
    - NPM_TOKEN=<add npm token>
